# Generated by Django 4.0.4 on 2022-04-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bananagrams', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
